# Generated by Django 5.2.4 on 2025-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('idea_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('none', 'None'), ('wedding', 'Marriage / Wedding'), ('birthday', 'Birthday Party'), ('anniversary', 'Anniversary Celebration'), ('corporate', 'Corporate Event / Office Party'), ('engagement', 'Engagement Ceremony'), ('baby_shower', 'Baby Shower'), ('graduation', 'Graduation Party'), ('housewarming', 'Housewarming / Griha Pravesh'), ('festival', 'Festival Event (Eid, Pohela Boishakh, Christmas, etc.)'), ('concert', 'Concert / Music Event'), ('fashion_show', 'Fashion Show / Exhibition'), ('workshop', 'Workshop / Seminar'), ('sports', 'Sports Event / Tournament'), ('charity', 'Charity / Fundraising Event'), ('farewell', 'Farewell / Welcome Party')], max_length=30)),
                ('budget_estimate', models.IntegerField(default=0)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('catering_type', models.CharField(choices=[('none', 'None'), ('snacks', 'Snacks'), ('full', 'Full Meal')], default='none', max_length=20)),
                ('catering_items', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(choices=[('none', 'None'), ('agrabad', 'Agrabad'), ('bohoddarhat', 'Bohoddarhat'), ('chawkbazar', 'Chawkbazar'), ('gec', 'GEC'), ('jamal_khan', 'Jamal Khan'), ('new_market', 'New Market')], default='Agrabad', max_length=100)),
                ('venue', models.CharField(default='', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
