# Generated by Django 5.2.4 on 2026-01-17 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('participant', 'Participant')], max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='participation',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('wedding', 'Marriage / Wedding'), ('birthday', 'Birthday Party'), ('anniversary', 'Anniversary Celebration'), ('corporate', 'Corporate Event / Office Party'), ('engagement', 'Engagement Ceremony'), ('baby_shower', 'Baby Shower'), ('graduation', 'Graduation Party'), ('housewarming', 'Housewarming / Griha Pravesh'), ('festival', 'Festival Event (Eid, Pohela Boishakh, Christmas, etc.)'), ('concert', 'Concert / Music Event'), ('fashion_show', 'Fashion Show / Exhibition'), ('workshop', 'Workshop / Seminar'), ('sports', 'Sports Event / Tournament'), ('charity', 'Charity / Fundraising Event'), ('farewell', 'Farewell / Welcome Party')], default='none', max_length=30),
        ),
        migrations.CreateModel(
            name='OrganizerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.useraccount')),
            ],
        ),
    ]
