# Generated by Django 5.2.1 on 2026-01-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_useraccount_alter_participation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='catering_items',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='participation',
            name='date_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='fullmeal_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='selected_event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='snack_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='budget_estimate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participation',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participation',
            name='catering_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='participation_files/'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participation',
            name='preferred_date',
            field=models.DateField(default='2026-01-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participation',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
