# Generated by Django 5.2.1 on 2026-01-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_remove_participation_catering_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerevent',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='organizerevent',
            name='organizer',
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='budget_estimate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='category',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='organizer_files/'),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='idea_title',
            field=models.CharField(default='Untitled Idea', max_length=200),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='organizer_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='participant_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='participant_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='preferred_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='organizerevent',
            name='venue',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
